{{- if and (.Values.blockchain.metrics.enabled) (.Values.blockchain.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.blockchain.fullname" . }}-metrics
  namespace: {{ include  "chart.namespace" . }}
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.blockchain.name "name" "metrics") | nindent 4 }}
    {{- with .Values.blockchain.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.blockchain.metrics.service.annotations .Values.global.addPrometheusAnnotations }}
  annotations:
    {{- if .Values.global.addPrometheusAnnotations }}
    prometheus.io/port: {{ .Values.blockchain.metrics.service.servicePort | quote }}
    prometheus.io/scrape: "true"
    {{- end }}
    {{- range $key, $value := .Values.blockchain.metrics.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.blockchain.metrics.service.type }}
  {{- if and .Values.blockchain.metrics.service.clusterIP (eq .Values.blockchain.metrics.service.type "ClusterIP") }}
  clusterIP: {{ .Values.blockchain.metrics.service.clusterIP }}
  {{- end }}
  ports:
  - name: {{ .Values.blockchain.metrics.service.portName }}
    protocol: TCP
    port: {{ .Values.blockchain.metrics.service.servicePort }}
    targetPort: metrics
  selector:
    {{- include "chart.selectorLabels" (dict "context" . "name" .Values.blockchain.name) | nindent 4 }}
{{- end }}