{{- if and (.Values.blockchain.serviceAccount.create) (.Values.blockchain.enabled) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.blockchain.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "chart.blockchain.serviceAccountName" . }}
  namespace: {{ include  "chart.namespace" . }}
  {{- with .Values.blockchain.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.blockchain.name "name" .Values.blockchain.name) | nindent 4 }}
    {{- with .Values.blockchain.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}