{{- if and (eq "dydx_api" .Values.connect.settings.marketMapProvider) (.Values.connect.settings.oracleConfig) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-json
  namespace: {{ include  "chart.namespace" . }}
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.connect.name "name" .Values.connect.name) | nindent 4 }}
data:
  oracle.json: |
    {
      "providers": {
        "dydx_api": {
          "api": {
            "endpoints": [
              {
                "url": "https://dydx-api.polkachu.com"
              },
              {
                 "url": "dydx-grpc.polkachu.com:23890"
              }
            ]
          }
        }
      }
    }
{{- end }}
---
{{- if and (eq "osmosis_api" .Values.connect.settings.marketMapProvider) (.Values.connect.settings.oracleConfig) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-json
  namespace: {{ include  "chart.namespace" . }}
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.connect.name "name" .Values.connect.name) | nindent 4 }}
data:
  oracle.json: |
    {
      "providers": {
        "osmosis_api": {
          "api": {
            "endpoints": [
              {"url": "https://osmosis-api.polkachu.com"}
            ]
          }
        }
      }
    }
{{- end }}
