{{- if .Values.connect.extraEnvVars.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.connect.fullname" . }}-env-secrets
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.connect.name "name" .Values.connect.name) | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.connect.extraEnvVars.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end -}}