{{- if .Values.connect.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.connect.serviceAccountName" . }}
  namespace: {{ include  "chart.namespace" . }}
  labels:
    {{- include "chart.labels" (dict "context" . "component" .Values.connect.name "name" .Values.connect.name) | nindent 4 }}
    {{- with .Values.connect.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.connect.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.connect.serviceAccount.automountServiceAccountToken }}
{{- end }}
